---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template places a new multi-zone RDS instance into a VPC.  Currently only supports MySQL.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

# These show up in the console and are expected to be provided by the operator
Parameters:
    Project:
        Description: 'Project name this cluster is has been created for'
        Type: 'String'
        Default: 'Weapon-X'

    Creator:
        Description: 'Tool or person creating this cluster'
        Type: 'String'
        Default: 'CloudFormation'

    Environment:
        Description: 'Context the cluster will be used in.  Common values are production, testing and development.'
        Type: 'String'
        Default: 'development'

    Notes:
        Description: 'Notes to apply, normally edited in the console.'
        Type: 'String'
        Default: 'No notes'

    Engine:
        Description: 'The name of the database engine that you want to use for this DB cluster. '
        Type: 'String'
        Default: 'mysql'

    EngineVersion:
        Description: 'The version number of the database engine that you want to use.'
        Type: 'String'
        Default: '5.7.16'

    MasterUsername:
        Description: 'The master user name for the DB instance.'
        Type: 'String'
        Default: 'root'

    MasterUserPassword:
        Description: 'The password for the master database user.'
        Type: 'String'
        Default: 'MySQL0LQSyM'

    Subnets:
        Description: 'A list of subnets where to run the EC2 instances in.'
        Type: 'List<String>'

    AllocatedStorage:
        Description: 'The allocated storage size, specified in gigabytes (GB).'
        Type: 'String'
        Default: '16'

    StorageType:
        Description: 'The storage type associated with this DB instance. standard | gp2 | io1'
        Type: 'String'
        Default: 'gp2'

    DBInstanceClass:
        Description: 'The name of the compute and memory capacity classes of the DB instance.'
        Type: 'String'
        Default: 'db.t2.small'

    Port:
        Description: 'The port for the instance.'
        Type: 'String'
        Default: '3306'

    VPC:
        Type: AWS::EC2::VPC::Id
        Description: 'Which VPC the database should be deployed to.'

Resources:
    SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: 'Database traffic from anywhere'
            VpcId:
                Ref: 'VPC'
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort:
                      Ref: Port
                  ToPort:
                      Ref: Port
                  CidrIp: 0.0.0.0/0
            Tags:
                - Key: 'Name'
                  Value:
                      'Fn::Join': [ ':', [ 'RDS', !Ref 'AWS::StackName' ] ]
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'Database access from any host'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'No notes'

    InstanceParameterGroup:
        Type: AWS::RDS::DBParameterGroup
        Properties:
            Description: 'MySQL configuration'
            Family: 'MySQL5.7'
            Parameters:
                max_allowed_packet: 67108864
                lower_case_table_names: 1
                character_set_server: utf8
                collation_server: utf8_unicode_ci
            Tags:
                - Key: 'Name'
                  Value:
                      'Fn::Join': [ ':', [ 'RDS Instance', !Ref 'AWS::StackName' ] ]
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'MySQL settings'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value:
                      Ref: 'Notes'

    SubnetGroup:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: 'Subnets that the instances will reside in.'
            SubnetIds:
               Ref: Subnets
            Tags:
                - Key: 'Name'
                  Value:
                      'Fn::Join': [ ':', [ 'RDS Instance', !Ref 'AWS::StackName' ] ]
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'Subntets to insert RDS instances into'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value:
                      Ref: 'Notes'

    Database:
        Type: AWS::RDS::DBInstance
        Properties:
            AllocatedStorage:
                Ref: AllocatedStorage
            AllowMajorVersionUpgrade: false
            AutoMinorVersionUpgrade: true
            CopyTagsToSnapshot: true
            DBInstanceClass:
                Ref: DBInstanceClass
            DBParameterGroupName:
                Ref: InstanceParameterGroup
            DBSubnetGroupName:
                Ref: SubnetGroup
            Engine:
                Ref: Engine
            EngineVersion:
                Ref: EngineVersion
            MasterUsername:
                Ref: MasterUsername
            MasterUserPassword:
                Ref: MasterUserPassword
            MonitoringInterval: 0
            MultiAZ: true
            Port:
                Ref: Port
            PubliclyAccessible: true
            StorageType:
                Ref: StorageType
            Tags:
                - Key: 'Name'
                  Value:
                      'Fn::Join': [ ':', [ 'Database', !Ref 'AWS::StackName' ] ]
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'Database instance'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value:
                      Ref: 'Notes'
            VPCSecurityGroups:
               - !Ref SecurityGroup

Outputs:
    Address:
        Description: 'The connection endpoint for the database.'
        Value: !GetAtt Database.Endpoint.Address
    Port:
        Description: 'The port number on which the database accepts connections.'
        Value: !GetAtt Database.Endpoint.Port
